name: teamintervaltest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

